services:
  client:
    build: ./client
    container_name: causalNestClient
    ports:
      - ${CLIENT_PORT}
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./serializer.proto
        target: /app/serializer.proto
    # restart: always
    depends_on:
      - server
    networks:
        - net1

  server:
    build: ./server
    container_name: causalNestServer
    ports:
      - ${SERVER_PORT}
    volumes:
      - type: bind
        source: ./serializer.proto
        target: /app/serializer.proto
    # restart: always
    # depends_on:
    #   - db
    networks:
        - net1

volumes:
  postgres_data:

networks:
  net1:
    driver: bridge
