# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import serializer_pb2 as serializer__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in serializer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SerializerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Discovery = channel.unary_unary(
                '/Serializer/Discovery',
                request_serializer=serializer__pb2.SerialData.SerializeToString,
                response_deserializer=serializer__pb2.SerialData.FromString,
                _registered_method=True)
        self.Estimation = channel.unary_unary(
                '/Serializer/Estimation',
                request_serializer=serializer__pb2.SerialData.SerializeToString,
                response_deserializer=serializer__pb2.SerialData.FromString,
                _registered_method=True)
        self.Refutation = channel.unary_unary(
                '/Serializer/Refutation',
                request_serializer=serializer__pb2.SerialData.SerializeToString,
                response_deserializer=serializer__pb2.SerialData.FromString,
                _registered_method=True)
        self.Graphs = channel.unary_unary(
                '/Serializer/Graphs',
                request_serializer=serializer__pb2.SerialData.SerializeToString,
                response_deserializer=serializer__pb2.SerialData.FromString,
                _registered_method=True)


class SerializerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Discovery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Estimation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Refutation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Graphs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SerializerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Discovery': grpc.unary_unary_rpc_method_handler(
                    servicer.Discovery,
                    request_deserializer=serializer__pb2.SerialData.FromString,
                    response_serializer=serializer__pb2.SerialData.SerializeToString,
            ),
            'Estimation': grpc.unary_unary_rpc_method_handler(
                    servicer.Estimation,
                    request_deserializer=serializer__pb2.SerialData.FromString,
                    response_serializer=serializer__pb2.SerialData.SerializeToString,
            ),
            'Refutation': grpc.unary_unary_rpc_method_handler(
                    servicer.Refutation,
                    request_deserializer=serializer__pb2.SerialData.FromString,
                    response_serializer=serializer__pb2.SerialData.SerializeToString,
            ),
            'Graphs': grpc.unary_unary_rpc_method_handler(
                    servicer.Graphs,
                    request_deserializer=serializer__pb2.SerialData.FromString,
                    response_serializer=serializer__pb2.SerialData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Serializer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Serializer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Serializer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Discovery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Serializer/Discovery',
            serializer__pb2.SerialData.SerializeToString,
            serializer__pb2.SerialData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Estimation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Serializer/Estimation',
            serializer__pb2.SerialData.SerializeToString,
            serializer__pb2.SerialData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Refutation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Serializer/Refutation',
            serializer__pb2.SerialData.SerializeToString,
            serializer__pb2.SerialData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Graphs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Serializer/Graphs',
            serializer__pb2.SerialData.SerializeToString,
            serializer__pb2.SerialData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
