# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculator.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'calculator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\"(\n\x10OperationRequest\x12\t\n\x01\x61\x18\x01 \x01(\x01\x12\t\n\x01\x62\x18\x02 \x01(\x01\"/\n\x0eResultResponse\x12\x0e\n\x06result\x18\x01 \x01(\x01\x12\r\n\x05\x65rror\x18\x02 \x01(\t\")\n\nSerialData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\r\n\x05\x64\x61ta2\x18\x02 \x01(\x0c\x32\xf8\x01\n\nCalculator\x12+\n\x03\x41\x64\x64\x12\x11.OperationRequest\x1a\x0f.ResultResponse\"\x00\x12\x30\n\x08Subtract\x12\x11.OperationRequest\x1a\x0f.ResultResponse\"\x00\x12\x30\n\x08Multiply\x12\x11.OperationRequest\x1a\x0f.ResultResponse\"\x00\x12.\n\x06\x44ivide\x12\x11.OperationRequest\x1a\x0f.ResultResponse\"\x00\x12)\n\x0bTesteSerial\x12\x0b.SerialData\x1a\x0b.SerialData\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPERATIONREQUEST']._serialized_start=20
  _globals['_OPERATIONREQUEST']._serialized_end=60
  _globals['_RESULTRESPONSE']._serialized_start=62
  _globals['_RESULTRESPONSE']._serialized_end=109
  _globals['_SERIALDATA']._serialized_start=111
  _globals['_SERIALDATA']._serialized_end=152
  _globals['_CALCULATOR']._serialized_start=155
  _globals['_CALCULATOR']._serialized_end=403
# @@protoc_insertion_point(module_scope)
