services:
  client:
    build: ./client
    container_name: ${CLIENT_CONTAINER_NAME}
    ports:
      - ${CLIENT_PORT}
    volumes:
      - ./client:/app/client
      - type: bind
        source: ./teste.proto
        target: /app/teste.proto
    # restart: always
    depends_on:
      - server
      - db
    networks:
        - net1

  server:
    build: ./server
    container_name: server
    # container_name: ${SERVER_CONTAINER_NAME}
    ports:
      - ${SERVER_PORT}
    volumes:
      # - ./server:/app/server
      - type: bind
        source: ./teste.proto
        target: /app/teste.proto
        # target: /app/proto/teste.proto
    # restart: always
    depends_on:
      - db
    networks:
        - net1

  db:
    image: ${DATABASE_IMAGE}
    container_name: ${DATABASE_CONTAINER_NAME}
    environment:
      POSTGRES_DATABASE: ${DATABASE}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - ${DATABASE_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
        - net1

volumes:
  postgres_data:
  # proto_file:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: ./teste.proto


networks:
  net1:
    driver: bridge
